---
abstract: 'An enhanced populate method'
author:
  - 'John Napiorkowski <jjn1056@yahoo.com>'
build_requires:
  DBIx::Class: 0.08107
  ExtUtils::MakeMaker: 6.42
  File::Find: 0
  Path::Class: 0
  SQL::Translator: 0.09004
  Test::More: 0
  YAML::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Schema-PopulateMore
no_index:
  directory:
    - inc
    - t
requires:
  Data::Visitor: 0.25
  DateTimeX::Easy: 0.087
  List::MoreUtils: 0.22
  Module::Pluggable: 3.9
  Moose: 0.83
  MooseX::AttributeHelpers: 0.19
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
