---
abstract: 'An enhanced populate method'
author:
  - 'John Napiorkowski <jjn1056@yahoo.com>'
build_requires:
  DBIx::Class: 0.08010
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  YAML::Tiny: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-Schema-PopulateMore
no_index:
  directory:
    - inc
    - t
requires:
  Data::Visitor: 0.15
  DateTimeX::Easy: 0.082
  List::MoreUtils: 0.22
  Module::Pluggable: 3.8
  Moose: 0.48
  MooseX::AttributeHelpers: 0.09
  perl: 5.8.6
version: 0.04
