---
abstract: 'An enhanced populate method'
author:
  - 'John Napiorkowski, C<< <jjnapiork@cpan.org> >>'
  - 'John Napiorkowski <jjnapiork6@cpan.org>'
build_requires:
  DBIx::Class: 0.08123
  DateTime::Format::SQLite: 0.11
  ExtUtils::MakeMaker: 6.42
  File::Find: 0
  Path::Class: 0.19
  SQL::Translator: 0.11006
  Test::More: 0.96
  YAML::Tiny: 1.44
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Schema-PopulateMore
no_index:
  directory:
    - inc
    - t
requires:
  Data::Visitor: 0.27
  DateTimeX::Easy: 0.089
  List::MoreUtils: 0.22
  Module::Pluggable: 3.9
  Moose: 1.09
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
  repository: git@github.com:jjn1056/DBIx-Class-Schema-PopulateMore.git
version: 0.15
