---
abstract: 'An enhanced populate method'
author:
  - 'John Napiorkowski, C<< <jjnapiork@cpan.org> >>'
build_requires:
  DBIx::Class: 0.08127
  DateTime::Format::SQLite: 0.11
  ExtUtils::MakeMaker: 6.42
  File::Find: 0
  Path::Class: 0.23
  SQL::Translator: 0.11007
  Test::More: 0.98
  YAML::Tiny: 1.48
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: DBIx::Class::Schema::PopulateMore
name: DBIx-Class-Schema-PopulateMore
no_index:
  directory:
    - inc
    - t
requires:
  Data::Visitor: 0.27
  DateTimeX::Easy: 0.089
  List::MoreUtils: 0.30
  Module::Pluggable: 3.9
  Moose: 1.24
  parent: 0.224
  perl: 5.8.5
resources:
  homepage: http://search.cpan.org/dist/DBIx-Class-Schema-PopulateMore/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jjn1056/DBIx-Class-Schema-PopulateMore.git
version: 0.16
